name: Build and Publish Node.js Package

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      tag:
        description: "npm tag (e.g., latest, beta)"
        required: true
        default: "latest"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: pnpm install

      - name: Build Package
        run: pnpm run build

      - name: Extract version from package.json
        id: package-version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Publish to npm (Release)
        if: github.event_name == 'release'
        run: pnpm publish --no-git-checks --new-version ${{ steps.package-version.outputs.VERSION }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

      - name: Publish to npm (Manual)
        if: github.event_name == 'workflow_dispatch'
        run: pnpm publish --no-git-checks --new-version ${{ steps.package-version.outputs.VERSION }} --tag ${{ github.event.inputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
